### ISSUE TITLE
paths.tags  contain /

### ISSUE THREAD

**Issue by lifegit** [chenshuai2144/openapi2typescript#13]
paths.tags 存在以下情况 :

1. "tags" : [ "user" ]
2. "tags" : [ "user/pack/测试" ]
3. "tags" : [ "user/pack/news" ]
4. "tags" : [ "用户" ]

**结果**

`$ umi openapi` 

![image](https://user-images.githubusercontent.com/33006878/125770150-5fd08102-714d-4d5a-bf78-df9ae13a2d61.png)

1. user
没有修改
2. userpackceshi
删除 /  并且拼音
3. userpacknews
删除 / 
4. 用户
没有修改

**accident** 
2. 太长，不友好
4. 标签为中文且不存在\，结果文件名为中文

**希望** 
1. pinyin
2. const list = tags.split("/")
3. const res = list[list.length-1]

**结果**
1. user
2. ceshi
3. news
4. yonghu

**Comment by lifegit** [comment]
do you think it's a good idea ?

**Comment by lifegit** [comment]
I can submit PR if you like.

**Comment by chenshuai2144** [comment]
来吧，声音大就是对的
