### ISSUE TITLE
apiPrefix判断逻辑问题

### ISSUE THREAD

**Issue by TSjianjiao** [chenshuai2144/openapi2typescript#167]
https://github.com/chenshuai2144/openapi2typescript/blob/e875f3d32b738897af5c09e682f842387a763154/src/serviceGenerator.ts#L539C9-L544C20

如果`apiPrefix=‘app’`，请求地址是`applet/xxx/xxx/xx`，会导致进入这个判断，不会添加`app`前缀。

**Comment by rookie-luochao** [comment]
已经在 [openapi-ts-request](https://github.com/openapi-ui/openapi-ts-request/commit/83721a13c860c0b19f310e4dbe717c2d03347127) 修复这个问题
