### ISSUE TITLE
HTTP方法没有body，只有params时，生成类型的问题。

### ISSUE THREAD

**Issue by liuyang-kevin** [chenshuai2144/openapi2typescript#21]
我们发现swagger.json生成的时候，没有对params等参数生成描述。所以转换的时候直接转换为dict类型。

是否可以修改为，直接根据函数名强行生成对应的类型结构，并融合到模版当中

项目比较忙，所以直接改到能满足个人需求了，但是位置不是很好，入侵性比较强。提了pr。 

#21

**Comment by chenshuai2144** [comment]
发布咯
