### ISSUE TITLE
operationId 是哪里来的

### ISSUE THREAD

**Issue by k983551019** [chenshuai2144/openapi2typescript#3]
https://github.com/chenshuai2144/openapi2typescript/blob/2cbb8b1b9ee73f45f404e2b6e2c16b0be62a4e7b/src/serviceGenerator.ts#L355
使用的时候我的newApi里 没有operationId
`{
  path: '/api/Employee_Privilege_Auth/Delete/{id}',
  method: 'delete',
  tags: [ 'Employee_Privilege_Auth' ],
  summary: ' (Auth)',
  parameters: [ { name: 'id', in: 'path', required: true, schema: [Object] } ],
  responses: {
    '200': { description: 'Success', content: [Object] },
    '401': { description: 'Unauthorized' },
    '403': { description: 'Forbidden' }
  },
  security: [ { oauth2: [] } ]
}`

**Comment by chenshuai2144** [comment]
operationId 是自动生成的，你的后端可能偷懒了

**Comment by k983551019** [comment]
> operationId 是自动生成的，你的后端可能偷懒了

现在遇到个问题，后端API 使用大驼峰，我把他返回的字段存起来，然后用上openapi生成的api 类型，就会出现大小写对不上，怎么解决比较好。

**Comment by k983551019** [comment]
或者能不能给openapi增加个属性，是否使用小驼峰

**Comment by k983551019** [comment]
发现是 swagger 里就是小写
