### ISSUE TITLE
为什么生成的全是可选属性

### ISSUE THREAD

**Issue by scrapstation** [chenshuai2144/openapi2typescript#54]
我在后端已经区分了Nullable，并且生成了正确的openapi json
![image](https://user-images.githubusercontent.com/56467036/162481897-5539a4a2-5350-48bd-a575-648ce9fe3d4d.png)

但生成的TS type propertity全是可选的
![image](https://user-images.githubusercontent.com/56467036/162481964-cfda910d-6448-4b7f-a120-eb7ad34d1366.png)

缺点：调用登录接口的时候，无法提示params.mobile是必传的，
![image](https://user-images.githubusercontent.com/56467036/162481017-661a7661-a6b5-4557-b48c-85b6c7282931.png)

**Comment by chunbin1** [comment]
你好 最后是怎么解决这个问题的
