### ISSUE TITLE
请求参数 options?: { [key: string]: any }, 可以支持模板变量替换吗？

### ISSUE THREAD

**Issue by tolerance-go** [chenshuai2144/openapi2typescript#83]
比如 AxiosRequestConfig

**Comment by lorcannn** [comment]
我理解可以通过以下参数解决。
```
  /**
   * 模板文件的文件路径
   */
  templatesFolder?: string;
```

see: https://github.com/chenshuai2144/openapi2typescript/blob/7183ccc4d9311e6ee710a2b7b2aa7518a2a6c595/src/index.ts#L69C28-L69C28
